### ISSUE TITLE
d(...) is not a function

### ISSUE THREAD

**Issue by JuanM04** [blitz-js/babel-plugin-superjson-next#29]
https://codesandbox.io/s/clever-oskar-ltpop?file=/pages/index.js

```
next: 10.0.5
react: 17.0.1
react-dom: 17.0.1
superjson: 1.4.1
babel-plugin-superjson-next: 0.1.9
```

**Comment by Skn0tt** [comment]
Thanks for reporting this issue. I've created two reproduction test cases in #30, but I can't reproduce them locally. Do you also face these issue locally or is it just in the CodeSandbox? On which operating system are you?

**Comment by JuanM04** [comment]
It happened in my PC after updating next and other dependencies. I'm using WSL (ubuntu), but it also failed when I deployed it to Vercel

**Comment by JuanM04** [comment]
I downgraded to next v10.0.4 and it works. So, it has something to do with v10.0.5

**Comment by Skn0tt** [comment]
That's good to know! I'll look into the updates made in 10.0.5 then.

**Comment by ChGGse** [comment]
Getting the same issue, Tried downgrading to 10.0.4 but no luck. Still getting the same error.

```
./pages/[...username].tsx
TypeError: E:\libby\libby-web\pages\[...username].tsx: d(...) is not a function
```

Is there a fix coming out soon?

**Comment by Skn0tt** [comment]
We haven't yet found the root cause. I've asked for input on the Next.js contributors Slack, but haven't received  answers yet. Will open an issue next.

I suspect that this issue happens in specific setups only. Could you provide a repro, too?

**Comment by ChGGse** [comment]
> We haven't yet found the root cause. I've asked for input on the Next.js contributors Slack, but haven't received answers yet. I'm in contact with Prisma now, seems like they know more ([vercel/next.js#21043 (comment)](https://github.com/vercel/next.js/issues/21043#issuecomment-759608184))

Thanks for the update. I think I'll place the development of my webapp on hold for now until there's a conclusion/fix.

**Comment by JuanM04** [comment]
> Getting the same issue, Tried downgrading to 10.0.4 but no luck. Still getting the same error.

Maybe you downgraded wrong. I have to `yarn remove next && yarn add next@10.0.4` (without the `^`) to downgrade correctly. I downgraded wrong immeasurable times.

**Comment by ChGGse** [comment]
> > Getting the same issue, Tried downgrading to 10.0.4 but no luck. Still getting the same error.
> 
> Maybe you downgraded wrong. I have to `yarn remove next && yarn add next@10.0.4` (without the `^`) to downgrade correctly. I downgraded wrong immeasurable times.

Alright I rechecked the version and it was stuck on 10.0.5 but I removed then installed next@10.0.4 and it works again. Only issue now is that it isn't showing data on Prisma but that's a separate issue altogether.

**Comment by Skn0tt** [comment]
This indeed is a regression in Next.js 10.0.5. Bisecting lead me to https://github.com/vercel/next.js/pull/20586 as the root cause. I'm now further investigating it.

**Comment by Skn0tt** [comment]
Further digging led me to @babel/plugin-transform-react-jsx, which is updated in the aforementioned PR.

**Comment by Skn0tt** [comment]
Alright, so as a workaround I was able to make it work like this:

```diff
- export default function MyPage() {
+ function MyPage() {
    ..
  }

+ export default MyPage
```

This shows _very_ weird behaviour, though. The error also doesn't occur when JSX isn't used at all:
```
export default function AStringReturningComponent() {
  return "something something help me understand why this works"
}
```

**Comment by JuanM04** [comment]
> Can you confirm this?

Yes, it works. That's very odd

**Comment by Skn0tt** [comment]
This is probably the most intricate build chain issue I've ever worked on 😳 Let's hope that the Babel team has an idea ... https://github.com/babel/babel/issues/12631

**Comment by Skn0tt** [comment]
With the masterful help of @nicolo-ribaudo and @JLHwung, we were able to find a workaround, which works locally for me. @JuanM04 @ChGGse could you try out `0.1.9-fix-19-danger` (`npm install babel-plugin-superjson-next@danger`)? If that also works for you, I'll publish a patch update with that.

**Comment by JuanM04** [comment]
Yes, it works!!!

**Comment by Skn0tt** [comment]
Amazing! :D

**Comment by Skn0tt** [comment]
Published as v0.1.10.

What a ride! I'm really glad we solved this 🥳

**Comment by Skn0tt** [comment]
@allcontributors add JuanM04 for bug

**Comment by Skn0tt** [comment]
@allcontributors add ChGGse for bug

**Comment by ChGGse** [comment]
> With the masterful help of @nicolo-ribaudo and @JLHwung, we were able to find a workaround.
> 
> @JuanM04 @ChGGse could you try out `0.1.9-fix-19-danger` (`npm install babel-plugin-superjson-next@danger`)? If that works for you, I'll publish a patch update with that. It works locally for me, so I'm positive on this ^^

I'll test it out in the morning when I wake up!
